var school-projects = {
    project: [
        {
            title:"Hungry Squid",
            time: "Spring 2015",
            school:"CMU",
            role:"Unity Developer",
            info:"Arcade Style Shooter's Google Tango Game ",
            platform:["Google Tangle"],
            development-tools:["Unity3D","NGUI","Parse BaaS"],
            description:"Hungry squid is an arcade style shooter's game that uses Google Tango's motion tracking. The player's goal is to find out all hidden strawberries in 3D worlds that were generated by other users. The players not only can shoot and destroy objects in the world to find the targets, but also can challenge others by creating a difficult map. ",
            outcome:"Our game, Hungry Squids was a selected demo game at Google booth, GDC 15",
            icon:"image/etc/hungrysquid-icon.png",
            promo:"https://youtu.be/DJBOhu9PvhM",
            images:[
                {
                    info:"Play Mode: Walking",
                    url:"image/etc/hungrysquid-playmode-1.png"
                },
                {
                    info:"Play Mode: Destroy Objects",
                    url:"image/etc/hungrysquid-playmode-2.png"
                },
                {
                    info:"Create Map",
                    url:"image/etc/hungrysquid-createmode.png"
                },
                {
                    info:"Map Interface",
                    url:"image/etc/hungrysquid-share.png"
                },
                {
                    info:"Leader Board",
                    url:"image/etc/hungrysquid-leaderboard.png"
                }
            ]
        },
        {
            title:"Marioneta",
            time:"Fall 2014",
            client:"Pittsburgh Children's Museum"
            role:"Unity Developer"
            info:"2 Player Kinect Experience to Interact as a Puppet",
            platform:["Kinect v2"],
            development-tools:["Unity3D"],
            description:"Marioneta is an installation which presents puppets in a 3D virtual reality environment, which museum guests can control with their bodies via the Microsoft Kinect 2. The puppets featured in our project are based on a collection of puppets donated to the Children’s Museum by Margo Lovelace, most of which are too delicate to be played with. We aim to create an engaging and intuitive experience which appeals to guests of all ages.",
            outcome:["This interactive experience was installed in Pittsburgh Children's Museum","This project got accepted by SXSW 15 and IEEE VR 15"],
            icon:"image/etc/marioneta-icon.png",
            promo:"https://youtu.be/DKYC4Ey70Rk",
            images:[
                {
                    info:"Marioneta",
                    url:"image/etc/marioneta-main.png"
                },
                {
                    info:"Players Need to Step into Change Puppet Area to Change Puppet",
                    url:"image/etc/marioneta-floor.png"
                },
                {
                    info:"Puppet Selection Interface",
                    url:"image/etc/marioneta-ui.jpg"
                }
            ],
            videos:[
                {
                    info:"Basic movements, Jump and Draw Particles by Waving Hands",
                    url:"https://youtu.be/wve7FqOeICI"
                },
                {
                    info:"Hit, Kick, Pickup, Throwing, Droping, Passing Objects to Other Player and Play intruments",
                    url:"https://youtu.be/iizWjLs3zD8"
                }

            ]
        }
    ]
};
